# Generated by Django 5.2.8 on 2026-03-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assujettis',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=150, verbose_name='NOMS')),
                ('sexe', models.CharField(max_length=1, verbose_name='SEXE')),
                ('date', models.DateField(blank=True, null=True, verbose_name='DATE')),
                ('adresse', models.CharField(max_length=150, verbose_name='ADRESSE')),
                ('telephone', models.CharField(max_length=15, verbose_name='TELEPHONE')),
                ('profession', models.CharField(max_length=50, verbose_name='PROFESSION')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='TELEPHONE')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('message', models.CharField(max_length=500, verbose_name='MESSAGE')),
                ('assujettis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contravention.assujettis', verbose_name='ID ASSUJETTIS')),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=254, verbose_name="DETAIL D'INFRACTION")),
                ('datein', models.DateTimeField(verbose_name="DATE D'INFRACTION")),
                ('lieu', models.CharField(max_length=150, verbose_name='LIEU')),
                ('assujettis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contravention.assujettis', verbose_name='ID ASSUJETTIS')),
            ],
        ),
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MONTANT')),
                ('datem', models.DateTimeField(verbose_name="DATE D'EMISSION")),
                ('status', models.CharField(max_length=20, verbose_name='STATUS')),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contravention.infraction', verbose_name='ID INFRACTION')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='numero')),
                ('datep', models.DateTimeField(verbose_name='DATE DE PAIEMENT')),
                ('mode', models.CharField(max_length=20, verbose_name='MODE DE PAIEMENT')),
                ('amende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contravention.amende', verbose_name='ID AMENDE')),
            ],
        ),
    ]
