# Generated by Django 4.2.5 on 2026-03-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contravention', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id',
            new_name='numero',
        ),
    ]
